/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppTodosRouteImport } from './routes/app/todos'
import { Route as AppSuccessRouteImport } from './routes/app/success'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAiRouteImport } from './routes/app/ai'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppSpacesIndexRouteImport } from './routes/app/spaces/index'
import { Route as AppSpacesSpaceIdRouteImport } from './routes/app/spaces/$spaceId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuccessRoute = AppSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSpacesIndexRoute = AppSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSpacesSpaceIdRoute = AppSpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/success': typeof AppSuccessRoute
  '/app/todos': typeof AppTodosRoute
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/spaces': typeof AppSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/success': typeof AppSuccessRoute
  '/app/todos': typeof AppTodosRoute
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/spaces': typeof AppSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/success': typeof AppSuccessRoute
  '/app/todos': typeof AppTodosRoute
  '/app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
  '/app/spaces/': typeof AppSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/login'
    | '/app/ai'
    | '/app/dashboard'
    | '/app/success'
    | '/app/todos'
    | '/app/spaces/$spaceId'
    | '/app/spaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/login'
    | '/app/ai'
    | '/app/dashboard'
    | '/app/success'
    | '/app/todos'
    | '/app/spaces/$spaceId'
    | '/app/spaces'
  id:
    | '__root__'
    | '/app'
    | '/(auth)/login'
    | '/app/ai'
    | '/app/dashboard'
    | '/app/success'
    | '/app/todos'
    | '/app/spaces/$spaceId'
    | '/app/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/todos': {
      id: '/app/todos'
      path: '/todos'
      fullPath: '/app/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/success': {
      id: '/app/success'
      path: '/success'
      fullPath: '/app/success'
      preLoaderRoute: typeof AppSuccessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/spaces/': {
      id: '/app/spaces/'
      path: '/spaces'
      fullPath: '/app/spaces'
      preLoaderRoute: typeof AppSpacesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/spaces/$spaceId': {
      id: '/app/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/app/spaces/$spaceId'
      preLoaderRoute: typeof AppSpacesSpaceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSuccessRoute: typeof AppSuccessRoute
  AppTodosRoute: typeof AppTodosRoute
  AppSpacesSpaceIdRoute: typeof AppSpacesSpaceIdRoute
  AppSpacesIndexRoute: typeof AppSpacesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSuccessRoute: AppSuccessRoute,
  AppTodosRoute: AppTodosRoute,
  AppSpacesSpaceIdRoute: AppSpacesSpaceIdRoute,
  AppSpacesIndexRoute: AppSpacesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
